### ISSUE TITLE
Rats (and sometimes other animals) crash the server on maptools pusher nodes.

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/issue-tracker#61]
Note, this is the trampoline that involves maptools pusher blocks pointed upwards.
The error:
```
2019-06-15 04:13:37: WARNING[Server]: collisionMoveSimple: Loop count exceeded, aborting to avoid infiniite loop
2019-06-15 04:13:37: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Invalid float vector dimension range 'y' (expected -2.14748e+06 < y < 2.14748e+06 got 3.16913e+32).
```
In this case, the rat was transported to what would be a million times the diameter of the observable universe. There is no special logic for this in maptools, it looks like it's an issue in core (possibly for things that have near-zero weight?)

This isn't necessarily only an issue with rats; they're just the most dependable way to cause this crash that I know of

**Comment by catwhisperer77** [comment]
Has this been fixed following the move to xdecor trampolines?

**Comment by fluxionary** [comment]
Mm, I suppose I should at least change the name of the issue to reflect the actual problem.

**Comment by luk3yx** [comment]
I moved the trampoline over to xdecor trampolines so it still works in the meantime, I plan to move it back to pushers once this is resolved.

**Comment by fluxionary** [comment]
Fixed this (though awating reboot). I forked mobs_redo, and wrote some code to bound the velocity of mobs to 10 m/s in the cardinal directions.
