### ISSUE TITLE
Admin smart shops can't currently be toggled to normal smartshops

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/issue-tracker#62]
See https://github.com/AiTechEye/smartshop/issues/5 upstream

**Comment by Panquesito7** [comment]
This might be the fix for the issue: https://github.com/AiTechEye/smartshop/issues/5#issuecomment-515827801.
Note that I haven't tested it, so, check it at your own risk.

**Comment by fluxionary** [comment]
I'm re-writing smartshops to fix numerous issues. This is already on that list.

**Comment by fluxionary** [comment]
Fixed this (not that there aren't other issues w/ smartshops still, see #137 )
