### ISSUE TITLE
Add item magnet

### ISSUE THREAD

**Issue by catwhisperer77** [BlockySurvival/issue-tracker#74]
Here's the item magnet mod from bhree's AitWL: https://github.com/bhree/minetest_aitwl_game/blob/06dd90ff29e4a9e0dfd8401313d6b552b3eeba95/minetest_game_local/mods/item_drop/init.lua

**Comment by Lanhild** [comment]
> For reference this is the other mod that shows up when I search for "magnet" on the forums: https://github.com/minetest-mods/item_drop
> It also does not do what I want, and is even more of a mess.

I searched for multiples item magnets mod, and this one ( the one you mentioned) seems to be the only one that is "properly" working.

**Comment by fluxionary** [comment]
I made an item magnet mod, if someone wants to use it:

https://github.com/fluxionary/minetest-item_magnet

**Comment by oversword** [comment]
Hmm that isn't quite what I was expecting, I think I might modify it so you can pick things up in your immediate vicinity by sneaking, and pick things up in a larger radius with the tool

**Comment by oversword** [comment]
https://github.com/BlockySurvival/minetest-item_magnet

**Comment by oversword** [comment]
This is done, as well as adding a crouch animation, you can now pick up items by crouching and also use the item magnet to draw items closer to you
