### ISSUE TITLE
Fix TP snipes

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/issue-tracker#83]
- [x] 1. Currently, `/tpr` and `/tphr` requests don't seem to time out, leading to strange behavior when a target accepts a request, and ends up triggering an old request instead. 
- [x] 2. ~~It'd be nice if `/tpr` and `/tphr` had an optional 2nd argument to override the default expiry period.~~ I think I was originally suggesting having an option to make it *shorter*, but I'm not really sure either is needed if things expire properly.
- [x] 3. There is no way for the source player to cancel a teleport request.
- [x] 4. Both players should get a notice when the request expires (or is cancelled).
- [ ] 5. If a targer player has multiple pending teleport requests, `/tpy` shouldn't just pick the first one chronologically, or however it's done. It should prompt them to chose from amongst the request, and accept it by name. 
- [x] 6. Players w/ admin (tp_admin?) privs shouldn't immediately tp a player when issuing a command; I can already do that w/ `/teleport`, and I still want to use those commands to issue requests.

We should also review all the features added in the forks: https://github.com/ChaosWormz/teleport-request/network/members

**Comment by fluxionary** [comment]
There was recently a big update to teleport-request, but I haven't fully reviewed it yet. Possibly it fixes some of these issues.

**Comment by thomasrudin** [comment]
Point 1 is fixed with https://github.com/ChaosWormz/teleport-request/pull/11

**Comment by Panquesito7** [comment]
> There is no way for the source player to cancel a teleport request.

Will try to add this feature (soon?).

> Both players should get a notice when the request expires (or is cancelled).

This has been added in ChaosWormz/teleport-request#12.

> It'd be nice if /tpr and /tphr had an optional 2nd argument to override the default expiry period

Players could use a large duration of expiry period (e.g.: 1000 seconds or something similar).
Perhaps only people with privileges like `tp_admin` could do this?

**Comment by Panquesito7** [comment]
> Players w/ admin (tp_admin?) privs shouldn't immediately tp a player when issuing a command; I can already do that w/ `/teleport`, and I still want to use those commands to issue requests.

This has been added in ChaosWormz/teleport-request#12.

**Comment by fluxionary** [comment]
> This has been added in [ChaosWormz/teleport-request#12](https://github.com/ChaosWormz/teleport-request/pull/12).

Cool. However it still requires editing a source file, and since I'm not allowing dirty repos on the server anymore, and I don't want to create yet another server-specific fork for something so simple, I (or someone) is going to have to make another PR to turn this into a proper setting.

**Comment by Panquesito7** [comment]
> This has been added in ChaosWormz/teleport-request#12.

> Cool. However it still requires editing a source file, and since I'm not allowing dirty repos on the server anymore, and I don't want to create yet another server-specific fork for something so simple, I (or someone) is going to have to make another PR to turn this into a proper setting.

Oh, that's too bad; I now understand why it isn't marked as finished.
I'm currently trying to add these features:
> There is no way for the source player to cancel a teleport request. 

> If a targer player has multiple pending teleport requests, /tpy shouldn't just pick the first one chronologically, or however it's done. It should prompt them to chose from amongst the request, and accept it by name.

I'm not that good in coding, so, I'll probably not add them, or it will be buggy or will result in a crash. 
Anyway, I'll keep you informed.

**Comment by Panquesito7** [comment]
> > This has been added in [ChaosWormz/teleport-request#12](https://github.com/ChaosWormz/teleport-request/pull/12).
> 
> Cool. However it still requires editing a source file, and since I'm not allowing dirty repos on the server anymore, and I don't want to create yet another server-specific fork for something so simple, I (or someone) is going to have to make another PR to turn this into a proper setting.

Looks like it has been updated (https://github.com/BlockySurvival/teleport-request).

> ~It'd be nice if /tpr and /tphr had an optional 2nd argument to override the default expiry period.~ I think I was originally suggesting having an option to make it shorter, but I'm not really sure either is needed if things expire properly.

This can be done by modifying `settingtypes.txt`, or by going to the settings tab on MT.
It was added in ChaosWormz/teleport-request#14.

**Comment by Panquesito7** [comment]
> 3. There is no way for the source player to cancel a teleport request.

ChaosWormz/teleport-request#32

**Comment by Panquesito7** [comment]
> 5. If a target player has multiple pending teleport requests, `/tpy` shouldn't just pick the first one chronologically, or however it's done. It should prompt them to chose from amongst the request, and accept it by name.

This is possible by creating a new table having the old values, and then re-writing the values in the original table.

However, if more than two players send a request to one player, it will just accept the last two requests from the last two players.

We can create at least 10 tables (which is not a good way to fix this, IMO); I don't think a player will receive more than 10 requests.

**Comment by Lanhild** [comment]
> 3. There is no way for the source player to cancel a teleport request.

doing /tpn will deny the teleport request you've just sent

**Comment by fluxionary** [comment]
oh really? neat, let me test that. must have been a recent update.

**Comment by fluxionary** [comment]
neat, it works. only 1 feature left.

**Comment by Lanhild** [comment]
Am working on the last one, might be able to finish it by tommorow evening

**Comment by Panquesito7** [comment]
Great! Glad to know everything is working. 🙂
If you find any issues, please report them at [ChaosWormz/teleport-request](https://github.com/ChaosWormz/teleport-request).

@Lanhild good to know you're working on this. If your feature works properly, could you submit a PR at [ChaosWormz/teleport-request](https://github.com/ChaosWormz/teleport-request)? Thanks.

**Comment by Panquesito7** [comment]
Any updates on this? @Lanhild.

**Comment by oversword** [comment]
This may be related to / the same as the issue I made here https://github.com/BlockySurvival/issue-tracker/issues/320

**Comment by oversword** [comment]
This is fixed by this MR
https://github.com/BlockySurvival/teleport-request/pull/4

If there are multiple requests pending it now opens a form for you to choose from them
