### ISSUE TITLE
Make the mailbox:mailbox work like an ender chest

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/issue-tracker#84]
I'd love it if i didn't have to visit every mailbox i have on the map to check my mail.

Because mailboxes have existing inventories, this should probably be implemented as an optional feature, e.g. a check-box in the UI that converts the mailbox from a local inventory to a player-attached one.

**Comment by fluxionary** [comment]
luk: you mentioned you were working on this, so I've assigned it to you.

**Comment by luk3yx** [comment]
I have completed (and partially tested) this, however I am unsure where to put the checkbox to enable this. I'd also like to add a special mailbox where you can send mail to any player that has a "global storage" mailbox.
<details>
<summary>Current formspec</summary>

![Screenshot](https://user-images.githubusercontent.com/3182651/62999693-56763b80-bec3-11e9-8641-1f85caa1f8a3.png)
</details>

**Comment by fluxionary** [comment]
That looks great to me. What's wrong w/ the position you have that checkbox currently?

**Comment by luk3yx** [comment]
> That looks great to me. What's wrong w/ the position you have that checkbox currently?

Because of the weird way formspecs work without `real_coordinates[true]`, the top checkbox has a negative Y position. I don't think this matters, however.

**Comment by luk3yx** [comment]
Pushed to the [`global_storage`](https://github.com/BlockySurvival/mailbox/tree/global_storage) branch for now, I have tested this somewhat and haven't found any bugs.

**Comment by luk3yx** [comment]
The server appears to have been updated.
