### ISSUE TITLE
signs:paper_poster doesn't display right

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/issue-tracker#93]
In each paragraph, the first line looks fine, but all subsequent lines have white letters over the text, which makes it quite hard to read.

**Comment by fluxionary** [comment]
ExeVirus: that seems like a reasonable workaround...

**Comment by ExeVirus** [comment]
Okay PR sent to the bls_mods/Display_Modpack for the workaround. Simply switches all text to white and background to dark. Went extra mile and made the black texture "textured".

**Comment by fluxionary** [comment]
Accepted the PR and pulled it into BlS. Awaiting reboot.

**Comment by Lanhild** [comment]
The posters display half of the lines on black text. This is a big problem as the background is black too...

**Comment by oversword** [comment]
I believe this was fixed by xerox

**Comment by ExeVirus** [comment]
Awesome, will have to check it out with 5.4 then

**Comment by fluxionary** [comment]
I think I fixed it both times (white -> black background, then black -> white again), but I think the poster still doesn't look right depending on the client/server combination. 
:vomiting_face:
